# Generated by Django 4.2.3 on 2023-08-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ek_drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inforequest',
            name='company',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='email',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='message',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='name',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='phone',
            field=models.CharField(default='None', max_length=16),
        ),
    ]
